name = "calendar-worker"
main = "src/index.ts"
compatibility_date = "2024-06-06"


# Replace with your Cloudflare account ID before deploying.
account_id = "26ee46efc46cfaef25a75fbf7bdf1e61"

[vars]
GOOGLE_REDIRECT_URI = "https://calendar-worker.hectordev.workers.dev/auth/callback"

[[kv_namespaces]]
binding = "USERS_KV"
id = "e3ecaa4981484330aacdc8d1a038a8c9"



[observability]
enabled = true
